### ISSUE TITLE
更换官网工具  Change official website tools

### ISSUE THREAD

**Issue by KeRan213539** [nacos-group/nacos-group.github.io#156]
nacos 目前使用的官网工具为 docsite

但是 docsite 已经很久没更新. 许多使用docsite做官网的开源项目已经纷纷弃坑(比如dubbo)

nacos 官网仓库也收到很多 机器人提交的 升级依赖(漏洞修复)的PR

综上,建议更换官网工具. 经过调研, 觉得 [hugo](https://gohugo.io/) 不错,主题也很多, 下面列出一些我个人觉得不错的主题的演示连接,大家觉得那个不错的回复 编号 投票(序号与个人中意程度无关哈),当然也可以推荐您觉得不错的主题, [主题列表](https://themes.gohugo.io/)

>The official website tool currently used by Nacos is docsite.
>However, docsite has not been updated for a long time. Many open source projects using docsite as official website have been abandoned (such as Dubbo)
>Nacos official website repositories also received many PR submitted by robots to upgrade dependency (vulnerability repair)
>In summary, it is suggested to replace official website tools. After investigation, [hugo](https://gohugo.io/) is good and there are many themes. Here are some demonstration links of topics I personally think are good. We think that the good reply number vote, of course, you can also recommend the topics you think are good. [hugo themes](https://themes.gohugo.io/)

[1].  https://www.docsy.dev/
[2]. https://themes.gohugo.io/theme/hugo-theme-learn/en/
[3]. https://themes.gohugo.io//theme/hugo-theme-techdoc/
[4]. https://themes.gohugo.io/theme/kross-hugo-portfolio-template/
[5]. https://themes.gohugo.io/theme/raditian-free-hugo-theme/
[6]. https://themes.gohugo.io/theme/hugo-elate-theme/
[7]. https://themes.gohugo.io/theme/allegiant/
[8]. https://themes.gohugo.io//theme/hugo-theme-docport/docport-theme/

另外一个工具(Another tool):
[T1]. https://docsify.js.org/#/

**Comment by JemGeek** [comment]
[6]. 投票

**Comment by Xezeloh** [comment]
[2]

**Comment by jnan88** [comment]
[6]

**Comment by noday** [comment]
我也选过文档工具，最后目标是hugo，docsy

**Comment by horizonzy** [comment]
[6].投票

**Comment by paderlol** [comment]
[6]. 投票
>

**Comment by Maijh97** [comment]
[6]. 投票

**Comment by HungKuei** [comment]
https://themes.gohugo.io//theme/hugo-theme-docport/docport-theme/

**Comment by Tallrik** [comment]
[6]

**Comment by KeRan213539** [comment]
> https://themes.gohugo.io//theme/hugo-theme-docport/docport-theme/

[8]

**Comment by code4perfect** [comment]
6

**Comment by zhuyuanyuan2016** [comment]
[T1]. https://docsify.js.org/#/  技术文档，简单明了，拒绝花里胡哨。

**Comment by KeRan213539** [comment]
> [T1]. https://docsify.js.org/#/ 技术文档，简单明了，拒绝花里胡哨。

哈哈,我们这个是官网哦,不止有文档

**Comment by gaisicheng** [comment]
[6]

**Comment by zhuyuanyuan2016** [comment]
> > [T1]. https://docsify.js.org/#/ 技术文档，简单明了，拒绝花里胡哨。
> 
> 哈哈,我们这个是官网哦,不止有文档
> 也是呀~

**Comment by ShadowySpirits** [comment]
[6]. 投票

**Comment by lifaxin** [comment]
[1].还是应该有点质感，毕竟是官网。

**Comment by beidouyunyun** [comment]
[6]

**Comment by caojiele** [comment]
[6]

**Comment by IT-ACG** [comment]
很可惜，dubbo已经把[1]给用上了 @lifaxin
![image](https://user-images.githubusercontent.com/5277544/103841555-d4497100-50ce-11eb-88dc-e8f8f010b903.png)

**Comment by IT-ACG** [comment]
> 很可惜，dubbo已经把[1]给用上了 @lifaxin 
> ![image](https://user-images.githubusercontent.com/5277544/103841555-d4497100-50ce-11eb-88dc-e8f8f010b903.png)
@noday

**Comment by plusmancn** [comment]
[1] 投票

现在的文档工具还要限制在 Node 8.0，Mac M1 已经编译不起来了

**Comment by pirateskipper** [comment]
[1] 投票

**Comment by heimanba** [comment]
新的官网使用了Astro+ tailwind ： https://mp.weixin.qq.com/s/RqZJcSzO_v7AXz2MD5gGHQ

**Comment by Majidrazaee** [comment]
Please return my property.  They engraved all my information
