### ISSUE TITLE
wrong maillinglist

### ISSUE THREAD

**Issue by fangjianmin** [nacos-group/nacos-group.github.io#17]
https://nacos.io/en-us/docs/contributing.html
click the mailinglist   dev-nacos@googlegroups.com
when called the mail application, you will see the mailaddress changed to
dev-nacos subscribe@googlegroups.comg.

**Comment by caojiele** [comment]
> https://nacos.io/en-us/docs/contributing.html
> click the mailinglist [dev-nacos@googlegroups.com](mailto:dev-nacos@googlegroups.com)
> when called the mail application, you will see the mailaddress changed to
> dev-nacos [subscribe@googlegroups.comg](mailto:subscribe@googlegroups.comg).

Yes, Do you solve it?

**Comment by caojiele** [comment]
> https://nacos.io/en-us/docs/contributing.html
> click the mailinglist [dev-nacos@googlegroups.com](mailto:dev-nacos@googlegroups.com)
> when called the mail application, you will see the mailaddress changed to
> dev-nacos [subscribe@googlegroups.comg](mailto:subscribe@googlegroups.comg).

Good, I have to submit 'pr'.

**Comment by fangjianmin** [comment]
@i will solve it@
