### ISSUE TITLE
run npm i failed.

### ISSUE THREAD

**Issue by brotherlu-xcq** [nacos-group/nacos-group.github.io#181]
the node saas cannot found.
![image](https://user-images.githubusercontent.com/25661357/116501444-5ca08b80-a8e3-11eb-989f-54a5b026051d.png)
Node and npm version as below:
![image](https://user-images.githubusercontent.com/25661357/116501492-77730000-a8e3-11eb-8aa9-ae2da7202554.png)

**Comment by caojiele** [comment]
When running the project, take a look at the README.md. Your Node version is too high.

**Comment by JackSun-Developer** [comment]
@brotherlu-xcq I will add a document to guide the users to install with the correct version.
