### ISSUE TITLE
jsdelivr cdn 挂了导致打不开官网

### ISSUE THREAD

**Issue by onewe** [nacos-group/nacos-group.github.io#286]
建议更换掉 `jsdelivr`

**Comment by KomachiSion** [comment]
能换到哪里？ 有替代嘛？

**Comment by onewe** [comment]
https://github.com/nacos-group/nacos-group.github.io/blob/e79ece0e51a2f8aace6782d7b9bcaf7c7353caa0/index.html#L7
把这行换了就好,这个js用阿里的cdn应该没问题
