### ISSUE TITLE
[CI] Automaticlly build website

### ISSUE THREAD

**Issue by caojiele** [nacos-group/nacos-group.github.io#52]
Nacos website need manual build and deploy process at this moment, we need a CI job to do automaticlly. What is choice Jenkins or Travis ci?

**Comment by liangyuanpeng** [comment]
maybe Travis ci is better for build website

**Comment by caojiele** [comment]
> maybe Travis ci is better for website

Hi, Can you solve this problem?

**Comment by heimanba** [comment]
just use github action for ci
