### ISSUE TITLE
Hope user manual can search by keyword 

### ISSUE THREAD

**Issue by Ibrahimovic777** [nacos-group/nacos-group.github.io#61]
Noticed Nacos website has no search button, it will be nice if support search by keyword.

**Comment by caojiele** [comment]
Hi, would you please send a pull request to fix it ?

**Comment by Ibrahimovic777** [comment]
> Hi, would you please send a pull request to fix it ?

Ok, I try to do.

**Comment by caojiele** [comment]
> > Hi, would you please send a pull request to fix it ?
> 
> Ok, I try to do.

Please refer to the here:
https://github.com/apache/dubbo-website/pull/153/commits/6e52a533c48317c892552c03bce7baf58d69d67c
https://github.com/apache/dubbo-website/pull/153/commits/ac24ebfc43125587360d4c946cd70e933d90ca15

**Comment by Ibrahimovic777** [comment]
> > > Hi, would you please send a pull request to fix it ?
> > 
> > 
> > Ok, I try to do.
> 
> Please refer to the here:
> [apache/dubbo-website@6e52a53](https://github.com/apache/dubbo-website/commit/6e52a533c48317c892552c03bce7baf58d69d67c)
> [apache/dubbo-website@ac24ebf](https://github.com/apache/dubbo-website/commit/ac24ebfc43125587360d4c946cd70e933d90ca15)

OK :)
